#!/usr/bin/env bash
# Phantom weak-network harness (macOS): make this Mac the phone's relay and
# degrade that path with dummynet.
#
# Why: the acceptance case for the "subway" work is a lossy, high-latency,
# bandwidth-limited mobile link. A real ride is not reproducible (and cannot be
# repeated on demand), so the phone is pointed at this Mac instead and the Mac
# forwards to the real server at the IP layer — the tunnel still terminates on
# the real server, and the degradation is applied to the *packets*, not to a
# terminated TCP stream. That matters: a user-space proxy that terminates TCP
# would hide the loss from the phone's own TCP stack.
#
# Layout:
#
#   phone ──pf rdr──▶ Mac ──dummynet pipe──▶ VPS
#                      ▲
#                      └── replies carry NAT state back through the same pipe
#
# Usage:
#   scripts/weaknet-mac.sh setup   w2 --vps 203.0.113.10
#   scripts/weaknet-mac.sh status
#   scripts/weaknet-mac.sh teardown
#
# Profiles (delay per direction, so the RTT roughly doubles):
#   w1  commute jitter : 40 ms, 1% loss, 10 Mbit/s
#   w2  weak signal    : 100 ms, 3% loss, 2 Mbit/s
#   w3  tunnel outage  : 75 ms, 5% loss, 4 Mbit/s + 8 s of total loss every 40 s
#
# Everything lives in one pf anchor plus dummynet pipes, and teardown restores
# the ruleset that was loaded before setup. If this Mac runs another proxy or
# VPN, run `status` first and prefer the fallbacks documented in
# tests/PERF_WEAKNET_REPORT.md.
#
# Requires sudo (pfctl/dnctl/sysctl). The phone must be on the same LAN.

set -euo pipefail

if [[ "$(uname -s)" != "Darwin" ]]; then
    echo "ERROR: this harness needs macOS (pf + dummynet). " >&2
    echo "       On Linux use tc/netem; on the phone itself there is no usable tc." >&2
    exit 1
fi

ANCHOR="phantom.weaknet"
STATE_DIR="${TMPDIR:-/tmp}/phantom-weaknet"
ANCHOR_FILE="${STATE_DIR}/anchor.conf"
BACKUP_FILE="${STATE_DIR}/pf.before"
FORWARDING_FILE="${STATE_DIR}/forwarding.before"
BLACKOUT_PID_FILE="${STATE_DIR}/blackout.pid"
ENABLED_FILE="${STATE_DIR}/pf.was_enabled"

PROFILE=""
VPS=""
PORT="443"
PHONE_IP=""
LAN_IF=""
DRY_RUN=0

usage() {
    sed -n '2,40p' "$0"
    exit "${1:-0}"
}

die() {
    echo "ERROR: $*" >&2
    exit 1
}

# --- profile tables -------------------------------------------------------

profile_delay_ms() {
    case "$1" in
        w1) echo 40 ;;
        w2) echo 100 ;;
        w3) echo 75 ;;
        *) die "unknown profile '$1' (use w1, w2 or w3)" ;;
    esac
}

profile_loss() {
    case "$1" in
        w1) echo 0.01 ;;
        w2) echo 0.03 ;;
        w3) echo 0.05 ;;
        *) die "unknown profile '$1'" ;;
    esac
}

profile_bandwidth() {
    case "$1" in
        w1) echo 10Mbit/s ;;
        w2) echo 2Mbit/s ;;
        w3) echo 4Mbit/s ;;
        *) die "unknown profile '$1'" ;;
    esac
}

# --- discovery ------------------------------------------------------------

default_lan_if() {
    route -n get default 2>/dev/null | awk '/interface:/{print $2; exit}'
}

lan_ip_of() {
    ifconfig "$1" 2>/dev/null | awk '/inet /{print $2; exit}'
}

lan_subnet_prefix() {
    local ip="$1"
    echo "${ip%.*}"
}

# The phone is assumed to be the only other address of the form
# <subnet>.<x> that has an entry in the ARP table and is currently reachable.
guess_phone_ip() {
    local prefix="$1"
    arp -an 2>/dev/null | awk -v p="$prefix." '
        $2 ~ "\\("p { ip = $2; gsub(/[()]/, "", ip); print ip; exit }'
}

require_root() {
    if [[ "$(id -u)" -ne 0 ]]; then
        die "needs sudo: sudo $0 $*"
    fi
}

# --- rule generation ------------------------------------------------------

write_anchor() {
    local delay loss bw
    delay="$(profile_delay_ms "$PROFILE")"
    loss="$(profile_loss "$PROFILE")"
    bw="$(profile_bandwidth "$PROFILE")"

    mkdir -p "$STATE_DIR"
    cat > "$ANCHOR_FILE" <<EOF
# Generated by scripts/weaknet-mac.sh — profile ${PROFILE}
# Redirect the phone's tunnel traffic (it dials this Mac) to the real server,
# then shape both directions of that flow.
rdr pass on ${LAN_IF} inet proto tcp from ${PHONE_IP} to ${MAC_IP} port ${PORT} -> ${VPS} port ${PORT}
rdr pass on ${LAN_IF} inet proto udp from ${PHONE_IP} to ${MAC_IP} port ${PORT} -> ${VPS} port ${PORT}
# The VPS's replies have to reach us before they can be shaped.
pass in quick on ${LAN_IF} inet proto tcp from ${VPS} port ${PORT} to ${PHONE_IP}
pass in quick on ${LAN_IF} inet proto udp from ${VPS} port ${PORT} to ${PHONE_IP}
# Shape each direction exactly once: matching both "in" and "out" would apply
# the delay twice and silently double the RTT.
dummynet out quick on ${LAN_IF} inet proto tcp from ${PHONE_IP} to ${VPS} port ${PORT} pipe ${PIPE}
dummynet out quick on ${LAN_IF} inet proto udp from ${PHONE_IP} to ${VPS} port ${PORT} pipe ${PIPE}
dummynet out quick on ${LAN_IF} inet proto tcp from ${VPS} port ${PORT} to ${PHONE_IP} pipe ${PIPE}
dummynet out quick on ${LAN_IF} inet proto udp from ${VPS} port ${PORT} to ${PHONE_IP} pipe ${PIPE}
# Source-NAT the forwarded flow so the VPS's replies come back through us.
nat on ${LAN_IF} inet proto tcp from ${PHONE_IP} to ${VPS} port ${PORT} -> (${LAN_IF})
nat on ${LAN_IF} inet proto udp from ${PHONE_IP} to ${VPS} port ${PORT} -> (${LAN_IF})
EOF

    echo "[weaknet] profile ${PROFILE}: delay ${delay}ms/direction, loss ${loss}, bandwidth ${bw}"
    echo "[weaknet] ${PHONE_IP} -> ${MAC_IP}:${PORT} ~~> ${VPS}:${PORT} on ${LAN_IF}"
}

# --- setup / teardown -----------------------------------------------------

setup_harness() {
    # `--dry-run` only prints, so it deliberately works unprivileged.
    [[ "$DRY_RUN" -eq 1 ]] || require_root "setup ${PROFILE} --vps ${VPS}"

    local delay loss bw
    delay="$(profile_delay_ms "$PROFILE")"
    loss="$(profile_loss "$PROFILE")"
    bw="$(profile_bandwidth "$PROFILE")"
    write_anchor

    if [[ "$DRY_RUN" -eq 1 ]]; then
        echo "[weaknet] --dry-run: rules that would be applied"
        cat "$ANCHOR_FILE"
        echo "[weaknet] dnctl pipe ${PIPE} config bw ${bw} delay ${delay} plr ${loss} queue 100"
        return 0
    fi

    mkdir -p "$STATE_DIR"
    # Remember how the machine looked so teardown can put it back.
    pfctl -s info 2>/dev/null | grep -q "Status: Enabled" \
        && echo yes > "$ENABLED_FILE" || echo no > "$ENABLED_FILE"
    pfctl -sr > "$BACKUP_FILE" 2>/dev/null || true
    sysctl -n net.inet.ip.forwarding > "$FORWARDING_FILE"

    dnctl pipe "$PIPE" delete >/dev/null 2>&1 || true
    dnctl pipe "$PIPE" config bw "$bw" delay "$delay" plr "$loss" queue 100
    # Forwarding is what makes the Mac a relay rather than a dead end.
    sysctl -w net.inet.ip.forwarding=1 >/dev/null
    pfctl -E >/dev/null 2>&1 || true
    # Load into a dedicated anchor and make the main ruleset evaluate it.
    pfctl -a "$ANCHOR" -f "$ANCHOR_FILE"
    {
        cat "$BACKUP_FILE" 2>/dev/null || true
        echo "anchor \"${ANCHOR}\""
    } | pfctl -f -

    start_blackout_loop

    echo "[weaknet] active. Verify:"
    echo "  pfctl -a ${ANCHOR} -s rules"
    echo "  dnctl pipe ${PIPE} list"
    echo "[weaknet] point the phone at ${MAC_IP}:${PORT} (replace the host:port of"
    echo "          the phantom:// link you import; keep the key and psk)."
    echo "[weaknet] when finished: sudo $0 teardown"
}

# w3 needs a repeating total outage. dummynet has no scheduler, so the loss
# rate is flipped between the profile rate and 100% on a 40 s cycle.
start_blackout_loop() {
    if [[ "$PROFILE" != "w3" ]]; then
        return 0
    fi
    local loss
    loss="$(profile_loss "$PROFILE")"
    (
        while true; do
            sleep 32
            dnctl pipe "$PIPE" config plr 1.0 >/dev/null 2>&1 || exit 0
            sleep 8
            dnctl pipe "$PIPE" config plr "$loss" >/dev/null 2>&1 || exit 0
        done
    ) &
    echo $! > "$BLACKOUT_PID_FILE"
    echo "[weaknet] outage loop: 8 s of total loss every 40 s (pid $(cat "$BLACKOUT_PID_FILE"))"
}

stop_blackout_loop() {
    if [[ -f "$BLACKOUT_PID_FILE" ]]; then
        kill "$(cat "$BLACKOUT_PID_FILE")" >/dev/null 2>&1 || true
        rm -f "$BLACKOUT_PID_FILE"
    fi
}

teardown_harness() {
    require_root "$@"

    stop_blackout_loop
    pfctl -a "$ANCHOR" -F rules >/dev/null 2>&1 || true
    if [[ -f "$BACKUP_FILE" ]]; then
        pfctl -f "$BACKUP_FILE" >/dev/null 2>&1 || true
    fi
    if [[ -f "$ENABLED_FILE" && "$(cat "$ENABLED_FILE")" == "no" ]]; then
        pfctl -d >/dev/null 2>&1 || true
    fi
    if [[ -f "$FORWARDING_FILE" ]]; then
        sysctl -w "net.inet.ip.forwarding=$(cat "$FORWARDING_FILE")" >/dev/null
    else
        sysctl -w net.inet.ip.forwarding=0 >/dev/null
    fi
    dnctl pipe "$PIPE" delete >/dev/null 2>&1 || true
    echo "[weaknet] torn down (pf rules restored, forwarding restored, pipe deleted)"
}

status_harness() {
    echo "[weaknet] state dir: ${STATE_DIR}"
    if [[ -f "$ANCHOR_FILE" ]]; then
        echo "--- anchor rules ---"
        cat "$ANCHOR_FILE"
    else
        echo "(no anchor configured)"
    fi
    echo "--- dnctl ---"
    sudo dnctl list 2>&1 | head -20 || true
    echo "--- pf ---"
    sudo pfctl -s info 2>&1 | head -5 || true
    echo "--- forwarding ---"
    sysctl -n net.inet.ip.forwarding
    if [[ -f "$BLACKOUT_PID_FILE" ]]; then
        echo "outage loop pid: $(cat "$BLACKOUT_PID_FILE")"
    fi
}

# --- argument parsing -----------------------------------------------------

ACTION="${1:-}"
[[ -n "$ACTION" ]] || usage 2
shift || true

while [[ $# -gt 0 ]]; do
    case "$1" in
        w1|w2|w3) PROFILE="$1"; shift ;;
        --vps) VPS="${2:?}"; shift 2 ;;
        --port) PORT="${2:?}"; shift 2 ;;
        --phone-ip) PHONE_IP="${2:?}"; shift 2 ;;
        --interface) LAN_IF="${2:?}"; shift 2 ;;
        --dry-run) DRY_RUN=1; shift ;;
        -h|--help) usage 0 ;;
        *) die "unknown argument '$1'" ;;
    esac
done

PIPE=1
[[ -n "$LAN_IF" ]] || LAN_IF="$(default_lan_if)"
[[ -n "$LAN_IF" ]] || die "cannot determine the LAN interface; pass --interface"
MAC_IP="$(lan_ip_of "$LAN_IF")"
[[ -n "$MAC_IP" ]] || die "interface ${LAN_IF} has no IPv4 address"

case "$ACTION" in
    setup)
        [[ -n "$PROFILE" ]] || die "setup needs a profile (w1|w2|w3)"
        [[ -n "$VPS" ]] || VPS="${PHANTOM_VPS:-}"
        [[ -n "$VPS" ]] || die "setup needs the real server: --vps <ip> (or PHANTOM_VPS)"
        [[ -n "$PHONE_IP" ]] || PHONE_IP="$(guess_phone_ip "$(lan_subnet_prefix "$MAC_IP")")"
        [[ -n "$PHONE_IP" ]] || die "cannot guess the phone's IP; pass --phone-ip"
        setup_harness "$@"
        ;;
    teardown)
        teardown_harness "$@"
        ;;
    status)
        status_harness
        ;;
    -h|--help|help)
        usage 0
        ;;
    *)
        usage 2
        ;;
esac
